// Lista di esempio: un ciclo di due settimane come lo descrive
// doc/02-routine-alimentare.md. Da quando l'app genera la lista da sola
// (Step 9) resta come banco di prova dei test, che così lavorano su una
// lista realistica e sempre uguale.

import type { Lista } from './tipi'

export const listaEsempio: Lista = {
  id: 'esempio',
  creataIl: '2026-09-07T08:00:00.000Z',
  stato: 'corrente',
  voci: [
    {
      id: 'verdura',
      nome: 'Verdura',
      reparto: 'ortofrutta',
      origine: 'generata',
      comprata: false,
      elementi: [
        { nome: 'zucchine', comprato: false },
        { nome: 'melanzane', comprato: false },
        { nome: 'spinaci', comprato: false },
        { nome: 'peperoni', comprato: false },
      ],
    },
    {
      id: 'frutta',
      nome: 'Frutta',
      reparto: 'ortofrutta',
      origine: 'generata',
      comprata: false,
      elementi: [
        { nome: 'uva', comprato: false },
        { nome: 'pere', comprato: false },
        { nome: 'fichi', comprato: false },
        { nome: 'mele', comprato: false },
      ],
    },
    {
      id: 'carne_rossa-1',
      nome: 'manzo (fettine)',
      reparto: 'macelleria',
      categoria: 'carne_rossa',
      origine: 'generata',
      comprata: false,
    },
    {
      id: 'carne_rossa-2',
      nome: 'hamburger di manzo',
      reparto: 'macelleria',
      categoria: 'carne_rossa',
      origine: 'generata',
      comprata: false,
    },
    {
      id: 'carne_bianca-1',
      nome: 'petto di pollo',
      reparto: 'macelleria',
      categoria: 'carne_bianca',
      origine: 'generata',
      comprata: false,
    },
    {
      id: 'carne_bianca-2',
      nome: 'cosce di pollo',
      reparto: 'macelleria',
      categoria: 'carne_bianca',
      origine: 'generata',
      comprata: false,
    },
    {
      id: 'pesce-1',
      nome: 'salmone (filetto)',
      reparto: 'pescheria',
      categoria: 'pesce',
      origine: 'generata',
      comprata: false,
    },
    {
      id: 'pesce-2',
      nome: 'orata',
      reparto: 'pescheria',
      categoria: 'pesce',
      origine: 'generata',
      comprata: false,
    },
    {
      id: 'pesce-3',
      nome: 'merluzzo',
      reparto: 'pescheria',
      categoria: 'pesce',
      origine: 'generata',
      comprata: false,
    },
    {
      id: 'pesce-4',
      nome: 'gamberi',
      reparto: 'pescheria',
      categoria: 'pesce',
      origine: 'generata',
      comprata: false,
    },
    {
      id: 'formaggio-1',
      nome: 'mozzarella di bufala',
      reparto: 'salumi_formaggi',
      categoria: 'formaggio',
      origine: 'generata',
      comprata: false,
    },
    {
      id: 'formaggio-2',
      nome: 'stracchino',
      reparto: 'salumi_formaggi',
      categoria: 'formaggio',
      origine: 'generata',
      comprata: false,
    },
    {
      id: 'affettati-1',
      nome: 'prosciutto crudo',
      reparto: 'salumi_formaggi',
      categoria: 'affettati',
      origine: 'generata',
      comprata: false,
    },
    {
      id: 'affettati-2',
      nome: 'bresaola',
      reparto: 'salumi_formaggi',
      categoria: 'affettati',
      origine: 'generata',
      comprata: false,
    },
    {
      id: 'uova-1',
      nome: 'uova',
      reparto: 'latticini_uova',
      categoria: 'uova',
      origine: 'generata',
      comprata: false,
    },
    {
      id: 'uova-2',
      nome: 'uova',
      reparto: 'latticini_uova',
      categoria: 'uova',
      origine: 'generata',
      comprata: false,
    },
    {
      id: 'manuale-1',
      nome: 'caffè',
      reparto: 'dispensa',
      origine: 'manuale',
      comprata: false,
    },
    {
      id: 'manuale-2',
      nome: 'detersivo piatti',
      reparto: 'casa_igiene',
      origine: 'manuale',
      comprata: false,
    },
  ],
}
